const teamData = [
    {
      position: 'President',
      name: 'Amaira Aggarwal',
      image: '/images/amaira.jpg',
      instagram: 'https://www.instagram.com/amairaa_agg?igsh=MTk0enJyNmQzd212ag%3D%3D&utm_source=qr',
      branch: 'MAE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/amaira-aggarwal-981b73283',
      twitter: '',
    },
    {
      position: 'President',
      name: 'Nandini Bansal',
      image: '/images/nandini.jpg',
      instagram: ' https://www.instagram.com/im__peehu?igsh=MWgxNHlnMTVkNHAyaQ== ',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/nandinibansal1524/',
      twitter: '',
    },
    {
      position: 'Secretary',
      name: 'Urvashi Yadav',
      image: '/images/UrvashiYadavSec.png',
      instagram: 'https://www.instagram.com/urvashi2004/',
      phone: '8595712096',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/urvashiyadav2004',
      twitter: '',
    },
    {
      position: 'Secretary',
      name: 'Daisy Sorokhaibam',
      image:'/images/DaisySorokhaibamSecretary.png',
      instagram: 'https://www.instagram.com/daisythekermit/',
      branch: 'CSEAI',
      year: '4',
      linkedin: 'https://www.linkedin.com/in/daisy-sorokhaibam-0bab4a280/',
      twitter: '',
    },  
    
    {
      position: 'WebD Lead',
      name: 'Anshika Sharma',
      image: '/images/AnshikaSharma_Webd.png',
      instagram: 'https://www.instagram.com/anshikaa_2024/',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/anshika-sharma-8b578822a ',
      twitter: '',
    },

    {
      position: 'Media Lead',
      name: 'Arzoo Patra',
      image: '/images/ArzooPatra_MediaTeam_Lead.jpg',
      email: '',
      instagram: '',
      branch: 'CSE',
      year: '3',
      linkedin: '',
      twitter: '',
    },
    {
      position: 'Content lead',
      name: 'Shreya Tejan',
      image: '/images/shreya_tejan.jpg',
      instagram: 'https://www.instagram.com/shreya_officio/ ',
      branch: 'ECE-AI',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/shreyatejan',
      twitter: '',
    },
    {
      position: 'EM lead',
      name: 'Shreya Gupta',
      image: '/images/Shreya Gupta_EM.jpg',
      email: '',
      instagram: '',
      phone: '',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/shreya-gupta-a783b9270?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ',
      twitter: '',
    },
   

    {
      position: 'PR lead',
      name: 'Vedanshi Mishra',
      image: '/images/VedanshiPrLead.png',
      email: '',
      instagram: '',
      phone: '',
      branch: '',
      year: '',
      linkedin: 'https://in.linkedin.com/in/vedanshi-mishra-315572280',
      twitter: '',
    },

    {
      position: 'Sponsorship Head',
      name: 'Siya Khetan',
      image: '/images/SiyaKhetanSponsiHead.png',
      email: 'megha081bteceai21@igdtuw.ac.in',
      instagram: 'https://www.instagram.com/_siyakhetan?igsh=MXJieHEwanFxMWp5NQ== ',
      phone: '9818472407',
      branch: 'ECEAI',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/siya-khetan-b95267252?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
      twitter: '',
    },
  ];
  
  export default teamData;
  

